### ISSUE TITLE
Naming of methods?

### ISSUE THREAD

**Issue by alahiff** [simvue-io/client#10]
We should decide if all of the methods are named appropriately or if we want to make any changes. Currently have:
* `init`
* `metadata`
* `event`
* `log`
* `save`
* `set_status`
* `close`
* `set_folder_details`
* `add_alert`

One thing I'm not sure about is `log`, as that doesn't immediately imply "metrics" to me - sounds more like a textual log message or something.

**Comment by AbyAbraham21** [comment]
Agreed. log clashes with the logging that I am adding for status/error. Change to metrics_log?

**Comment by alahiff** [comment]
Possibly, that's better. I'll check what ML experiment tracking / distributed tracing people use in order to get some ideas/see if there's anything consistently used in different projects. `log` actually came from one ML experiment tracking platform.

**Comment by alahiff** [comment]
How about either `log_metrics`, `add_metrics` or `metrics`?

**Comment by AbyAbraham21** [comment]
I would suggest log_metrics as it is clear then
