### ISSUE TITLE
Support API of the v2 backend

### ISSUE THREAD

**Issue by alahiff** [simvue-io/client#108]
The client should support both the v1 and v2 backends transparently.

Runs
- [x] Run creation
- [x] Set folder details
- [x] Artifacts
- [x] Metrics
- [x] Events
- [x] Update status
- [x] Update tags
- [x] Update metadata
- [x] Define alert
- [x] Add alert to run
- [x] Offline mode

Client
- [x] Retrieve runs
- [x] Delete runs
- [x] List artifacts
- [x] Get artifacts (as file/normal)
- [x] Get Folders
- [x] Get Metrics (single/multiple)*
- [x] Delete Folders
- [x] Get Events
- [x] Get Alerts 

* Converters need fixing

**Comment by kzscisoft** [comment]
@alahiff am I right in thinking we are now dropping v1 support moving forward?
