### ISSUE TITLE
Matplotlib is not installed as a dependency for Simvue

### ISSUE THREAD

**Issue by wk9874** [simvue-io/client#114]
Currently Matplotlib is not a dependency for the Simvue package, although it is required for methods such as `plot_metrics()`. 

Will need to decide whether we want to include this as a dependency (but this will mean increasing the number of installations to support methods which most users may not use), make it an optional dependency, or just to change the docs to make clear to users that they will need to manually install matplotlib if using any of the plotting methods.

**Comment by kzscisoft** [comment]
This is handled by #137 which uses Poetry for dependency specification, extras have been created for optional installs:

```sh
pip install client[plot,torch,dataset]
```

**Comment by kzscisoft** [comment]
Closed by #149
