### ISSUE TITLE
Runs created on separate processes do not send any metrics

### ISSUE THREAD

**Issue by james-panayis** [simvue-io/client#122]
When a Run object is created on a separate process, no metrics are logged. On the other hand, it works perfectly if a thread is used instead of a process (see the commented out line):

```
'''Send some metrics to Simvue and then check them'''

from simvue import Run, Client
import random
import time
import threading
from multiprocessing import Process

def upload(name: str, metrics_per_run: int, microseconds_between_metrics: int):
    '''Send some data to Simvue'''
    print("Creating run:", name)

    run = Run()
    run.init(name=name,
             metadata={'meta_1.num_classes': 1,
                       'meta_1.num_units': "units_1"})
    run.save('example.py', 'code')

    for i in range (metrics_per_run):
        run.log_metrics({'increment': i})
        time.sleep(microseconds_between_metrics / 1000000)

    time.sleep(5)
    run.close()
    time.sleep(5)


if __name__ == "__main__":
    name = 'Test-'+str(random.randint(0, 1000000000))
    metrics_per_run = 10

    #thread = threading.Thread(target=upload, args=(name, metrics_per_run, 100000)) # works with this
    thread = Process(target=upload, args=(name, metrics_per_run, 100000)) # does NOT work with this
    thread.start()
    thread.join()

    time.sleep(10)

    print("\nchecking data consistency\n")

    client = Client()
    metrics = client.get_metrics(name, 'increment', 'step')

    if len(metrics) != metrics_per_run:
        print(f"error - incorrect number of metrics in run (expected {metrics_per_run}, got  " + str(len(metrics)) +")")
        exit()

    for i in range(len(metrics)):
        if i != int(metrics[i][1]):
            print(f"error - inconsistent metrics in run (expected {i}, got " + str(metrics[i][1]) +")")
            exit()

    print(f"\ntesting successful")
```

**Comment by alahiff** [comment]
The client currently is not designed to support having a single client running across multiple processes, so this is as expected. This could be important for people doing more advanced things with Python (e.g. using Dask or similar) but we don't currently have any example use cases requiring this.

(Initially the more important scale test is multiple independent clients running concurrently in separate processes, representing many independent simulations being run in parallel).

**Comment by james-panayis** [comment]
I am probably misunderstanding something here, but I don't have a single client running across multiple processes. Here the main process creates a second process. This second process then creates a Run object, sends some metrics, and then closes the run. The metrics it tries to send don't get stored by Simvue. Everything that happens after the `time.sleep(10)` is just to demonstrate that the data has not been recorded (though this can alternatively be seen on the Simvue website).

Currently it seems that sending data from any process other than the main one is not supported (in which case the only action currently needed to address this issue would be to document this, ideally warning users if they attempt it)

(Regarding scalability testing, yes I will run separate instances of the same program, instead of one instance which creates multiple processes)

**Comment by alahiff** [comment]
Sorry, I misunderstood. Running the Simvue client in a separate process has never been used or tested yet, so it's quite possible there is a bug or limitation preventing this from working. I would have expected it to work however. The Run object creates a worker thread which sends the metrics. So in your case I would have expected each process created by the main process to have its own worker thread.

The code relating to the worker thread can almost certainly be significantly improved/re-written.

**Comment by alahiff** [comment]
There should only be at most one worker thread per Simvue client, having more than one would be a bug.

**Comment by kzscisoft** [comment]
Could this be a very short workaround for limiting calls:
https://stackoverflow.com/a/50441345

**Comment by james-panayis** [comment]
> If the Simvue client is not the top-most process, then that's a situation that hasn't been considered yet.

Ah... it might be worth considering. :wink: Because it would be useful for our optimization code, which wants to set off a set of runs simultaneously (and so from different processes).

**Comment by alahiff** [comment]
Yes, we definitely should support this situation (and add a test to make sure it works).

**Comment by alahiff** [comment]
> Could this help with reducing the code towards rate limiting:
> https://stackoverflow.com/a/50441345

I assume this is meant for another thread? :-)

**Comment by james-panayis** [comment]
> Shouldn't there be a client for each run?

Yes, each process creates its own `Run` object.

**Comment by james-panayis** [comment]
This is now fixed :tada:
