### ISSUE TITLE
Handle Invalid Tag Values

### ISSUE THREAD

**Issue by kzscisoft** [simvue-io/client#132]
Currently the user can provide any string as a tag, I only discovered this issue because I accidentally submitted a tag in the form `"my-[tag, value]"` which likely caused issues on the server in terms of parsing.

It would be good to have tag checking at the client level.

**Comment by alahiff** [comment]
The server should give a 422 in this situation, or at least the current version does. The Pydantic model for the tag uses the following for the `name`:

```
constr(regex=r'^[\w\-\s.]+$')
```

But yes, I agree the client should check first.

**Comment by alahiff** [comment]
I just checked dev02 and it has an older version. Once updated (will do before Monday) it will give a 422.

**Comment by kzscisoft** [comment]
@alahiff  feel free to close this after 🙂

**Comment by alahiff** [comment]
Closing as I have merged your pull request and checked that the error message makes much more sense :-)
