### ISSUE TITLE
Minimum Python version?

### ISSUE THREAD

**Issue by alahiff** [simvue-io/client#141]
What is the minimum Python version required for the executor code? I'm guessing it's quite a recent version of Python?

On the STFC cloud the most recent Ubuntu VMs are Ubuntu 20.04 and have Python 3.8. Running the Simvue client gives this error:
```
  File "/home/ubuntu/.local/lib/python3.8/site-packages/simvue/executor.py", line 25, in <module>
    class Executor:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/simvue/executor.py", line 57, in Executor
    executable: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
In order to use the client at all I need to comment out all usage of `Executor`.

**Comment by kzscisoft** [comment]
@alahiff this looks like just a typing issue, I am guessing the use of `|` in typing is not supported within Python3.8, this is PEP604:

https://peps.python.org/pep-0604/

**Comment by kzscisoft** [comment]
As discussed, given that for most of our dependencies the minimum supported version of latest releases is now Python3.9, this should become our minimum also. This is definitely recommended if we decided to adopt #149 .
