### ISSUE TITLE
Rename Simvue class

### ISSUE THREAD

**Issue by alahiff** [simvue-io/client#18]
At the moment there's a class called `Simvue` which is used for creating runs. Since we want to be able to run queries etc from the client as well it would make sense to rename the existing class to something more suitable, e.g. to `Run` perhaps. So to create a run you'd use:
```
from simvue import Run

run = Run()
run.init()
...
```
The existing couple of methods related to download data etc should be moved into a new class.

**Comment by AbyAbraham21** [comment]
Yes, that would make more sense. Will make it more structured and easier to test as well.

**Comment by alahiff** [comment]
As well as renaming the existing `Simvue` class as `Run`, should move the following methods into a new class, perhaps called `Client`:
* `list_artifacts`
* `get_artifact_as_file`
* `get_artifacts_as_files`

(The names include `as_file` because I want to have other versions which don't save to a file, e.g. for a numpy array you could just directly create a variable containing the contents of the artifact).

**Comment by alahiff** [comment]
Implemented in https://github.com/simvue-io/client/commit/db3bde87868bbdd3e8be602cb9638db07076f267
