### ISSUE TITLE
Colorama formatting of log messages makes performance drop

### ISSUE THREAD

**Issue by wk9874** [simvue-io/client#215]
Looks like the coloring of log messages within `utilities.py/print_nice()` causes simvue runs to slow down an incredible amount if iteratively creating them, becoming unusable after around 6/7 runs.

With the following code:
```
import simvue

for i in range(20):
    with simvue.Run() as run:
        run.init(f"test run {i}")
        print(f"Run {i}")
```
I see severe performance drops after the 6th run is created.

However inside `utilities.py`, if I change `print_nice()` to simply be `print(message)`, then I don't see any slow downs with the above script.

**Comment by james-panayis** [comment]
This was a fun one to hunt :smile:
