### ISSUE TITLE
Functionality to handle runs that have crashed

### ISSUE THREAD

**Issue by AbyAbraham21** [simvue-io/client#4]
There are cases where runs have crashed. One option is for the client to ping a heart beat to each run and check if they are still running.

**Comment by alahiff** [comment]
There's a working version of this in this branch: https://github.com/simvue-io/client/tree/heartbeat_thread

The threading stuff could be improved possibly. At the moment the heartbeat thread sleeps in 5 secs blocks, sending a heartbeat every 60s. So if you kill the code you need to wait up to 5 secs for it to stop, which is a bit annoying. Maybe just reducing this to 1 sec is the simplest option.

**Comment by AbyAbraham21** [comment]
Ok. Thanks. Will close this one.

**Comment by AbyAbraham21** [comment]
Duplicate
